## 문제 1~10
- 시도와 답과 다른 경우만 따로 표시할 예정

In [1]:
# 1
import numpy as np

In [2]:
# 2
data = [1, 2, 3]
np.array(data)

array([1, 2, 3])

In [3]:
# 3
np.arange(0, 99+1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
# 3번 답
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
# 4
np.arange(3, 27+1, 3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
# 4번 답
np.arange(1, 10) * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
# 5
np.arange(2, 1000, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 36

In [8]:
# 6
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [9]:
# 7
data = [0, 1, 2, 3, 4, 5]
np.array(data).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
# 8
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

arr.reshape(6,)

array([0, 1, 2, 3, 4, 5])

In [11]:
# 8번 정답
arr.flatten()

array([0, 1, 2, 3, 4, 5])

In [12]:
# 9
arr = np.arange(3)
arr.reshape(3, 1)

array([[0],
       [1],
       [2]])

In [13]:
# 10
np.arange(6).reshape(2, 4)

ValueError: cannot reshape array of size 6 into shape (2,4)

### 에러 원인 설명
- 요소가 총 6개인데 총 8개인 2x4 로 바꿈

In [14]:
# 10
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

## 문제 11 ~ 20

In [15]:
# 11
arr = np.array([[0, 1, 2],
 [3, 4, 5]])

In [16]:
# 12
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [17]:
# 12 정답
np.ones(20, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
# 13
np.ones(20, (4, 5), dtype=int)

TypeError: ones() got multiple values for argument 'dtype'

In [19]:
# 13 다시시도
np.ones((4, 5), dtype=int) 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
# 13 정답
np.ones(20, dtype=int).reshape(4, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
# 14
num = [255] * 100
np.array(num).reshape(10, 10)

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [22]:
# 14 정답
arr = np.ones(100, dtype=int).reshape(10, 10)
arr = arr * 255
arr

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [23]:
# 15
np.zeros((3, 4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
# 16
list = [1, 2, 3]
np.array(list, dtype=np.int32)

array([1, 2, 3])

In [25]:
# 16 정답
data = [1, 2, 3]
arr_s = np.ndarray(data, dtype=np.int32)
arr_s
# 또잉??????????

array([[[0, 1, 2],
        [3, 4, 5]]])

In [26]:
# 17
arr_1 = np.array([1, 2, 3])
np.dtypes(arr_1)

TypeError: 'module' object is not callable

In [27]:
# 17 정답
print(arr_1.dtype)

int32


In [28]:
# 18
arr = np.array(['1', '2', '3'])
arr.dtype

dtype('<U1')

In [29]:
# 19
arr = np.array([1, 2, 3])
np.ndarray(arr, dtype=np.int16)

array([[[49,  0, 50],
        [ 0, 51,  0]]], dtype=int16)

In [30]:
# 19 정답
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

In [31]:
# 20
a = np.array([ 255, 300, 128], dtype=np.uint8)
a

C:\Users\박해극\AppData\Local\Temp\ipykernel_7260\1541953962.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([ 255, 300, 128], dtype=np.uint8)


array([255,  44, 128], dtype=uint8)

### 20번 답
`uint8`은 부호 없는 8비트 정수를 표현합니다. 0부터 2^8 -1 범위의 수를 표현
범위의 수를 표현할 수 있습니다. 300은 `uint8`이 표현할 수 있는 범위를 넘기 때문에 잘못된 값이 출력됩니다.

## 문제 21~30

In [32]:
# 21
arr = np.array([1.1, 2.1, 3.1])
arr.astype(np.int32)

array([1, 2, 3])

In [33]:
# 22
np.linspace(0, 10, num=20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [34]:
# 23
arr = np.arange(9).reshape(3, 3)
arr[2]

array([6, 7, 8])

In [35]:
# 23 정답
arr[2]

array([6, 7, 8])

In [36]:
# 24
arr = np.arange(9).reshape(3, 3)
arr[:, 1]

array([1, 4, 7])

In [37]:
# 25
arr = np.arange(25).reshape(5, 5)
arr[2][2]

12

In [38]:
# 25 정답
arr[3, 2]

17

In [39]:
# 26
arr = np.arange(5)
arr[1:4:2]

array([1, 3])

In [40]:
# 26 정답
arr[[1, 3]]

array([1, 3])

In [45]:
# 27
arr = np.arange(25).reshape(5,5)
arr[1, 1:]

array([6, 7, 8, 9])

In [41]:
# 28
arr = np.arange(25).reshape(5, 5)
arr[:, 0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [42]:
# 29
arr = np.arange(25).reshape(5, 5)
arr[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [43]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
# 30 정
result = arr[[0, 0, -1, -1], [0, 3, 0, 3]].reshape(2, 2)
result

array([[ 0,  3],
       [20, 23]])

## 문제 31~40

In [50]:
# 31
data = [1, 2, 3]
np.array(data)*10

array([10, 20, 30])

In [56]:
# 32
arr = np.array(data)
list(map(lambda x: x*x, arr))

TypeError: 'list' object is not callable

In [57]:
# 32 정답
result = np.array(data) ** 2

In [60]:
# 33
np.array(data) ** 0.5

array([1.        , 1.41421356, 1.73205081])

In [59]:
# 33 정답
np.sqrt(data)

array([1.        , 1.41421356, 1.73205081])

In [67]:
# 34
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
print(np.mean(score[:,0]))
print(np.mean(score[:,1]))

12.0
18.0


In [68]:
# 34 정답
score.mean(axis=0)

array([12., 18.])

In [70]:
# 35
score.std(axis=1)

array([5., 1.])

In [71]:
# 36
a = np.arange(4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)
np.matmul(a, b)

array([[ 3,  4],
       [11, 16]])

In [73]:
# 37
arr = np.arange(9).reshape(3, 3)
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [76]:
# 38
arr = np.arange(10)
arr[0::2]

array([0, 2, 4, 6, 8])

In [77]:
# 39
arr[1::2]

array([1, 3, 5, 7, 9])

In [78]:
# 40
arr[(arr > 3) & (arr < 7)]

array([4, 5, 6])

## 문제 41~50

In [79]:
# 41
arr = np.array([-1, 2, -3, 4])
mask = arr < 0
arr[mask]

array([-1, -3])

In [80]:
# 42
arr[mask] = 0
arr

array([0, 2, 0, 4])

In [87]:
# 43
array = np.array([-1, 2, -3, 4])
np.array(__builtins__.list(map(lambda x: -x if x < 0 else x, array)))

array([1, 2, 3, 4])

In [88]:
# 43 정답
cond = array < 0
array[cond] = -array[cond]
# or abs(array)

In [89]:
# 44
num = np.array([-1, 2, -3, 4])
np.array(__builtins__.list(map(lambda x: x + 10 if x < 0 else x - 10, array)))

array([ 9, -8,  7, -6])

In [91]:
# 44 정답
np.where(num >= 0, num - 10, num + 10)

array([ 9, -8,  7, -6])

In [97]:
# 45
arr = [1, 2, 3, 4, 5]
np.random.shuffle(arr)
arr

[3, 5, 2, 4, 1]

In [98]:
# 46
arr = np.array([1, 2, 3, 4, 5])
np.argmin(arr)

0

In [99]:
# 47
np.argmax(arr)

4

In [100]:
# 48
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
# 49
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
np.vstack((arr1, arr2))

array([[1, 2],
       [3, 4]])

In [104]:
# 50
arr = np.array([[1, 2], [3, 4]])
np.ndarray.flatten(arr)

array([1, 2, 3, 4])